# -*- coding: utf-8 -*-
"""Teste de análise de similaridade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166dci_xrkL2KJQCg3C5U0gV1n21gOFy-
"""

# Teste avaliativo para seleção de bolsista de IC
# Tema: Análise de similaridade entre abstratos de artigos científicos
# Discente: Antonio Gilliard da Silva Sousa

''' Para realizar análises entre abstratos diferentes, basta modificar o índice do
objeto correspondente ao caminho do abstrato correspondente. Os abstratos estão na ordem
dos títulos passados no formulário da atividade.'''

# Instalando a biblioteca textdistance, específica para análise de similaridade entre strings:
! pip install textdistance

# Importando a biblioteca:
import textdistance as td

from google.colab import files

# Upload do arquivo .zip:
uploaded = files.upload()

# Extraindo o conteúdo do arquivo .zip:
import io

with zipfile.ZipFile(io.BytesIO(uploaded['abstratos_analise.zip']), 'r') as zip_ref:
    zip_ref.extractall('/content/analise_similaridade/')

print("Pasta extraída com sucesso.")

# Definindo função para ler o conteúdo de um arquivo
def ler_arquivo(nome_arquivo):
    with open(nome_arquivo, 'r') as arquivo:
        return arquivo.read()

# Tupla com os caminhos dos arquivos .txt com os abstratos de cada artigo selecionado para análise:

caminho_abstrato = ('/content/analise_similaridade/IC_PLN/texto1.txt', '/content/analise_similaridade/IC_PLN/texto2.txt',
                  '/content/analise_similaridade/IC_PLN/texto3.txt', '/content/analise_similaridade/IC_PLN/texto4.txt',
                  '/content/analise_similaridade/IC_PLN/texto5.txt', '/content/analise_similaridade/IC_PLN/texto6.txt',
                  '/content/analise_similaridade/IC_PLN/texto7.txt', '/content/analise_similaridade/IC_PLN/texto8.txt',
                  '/content/analise_similaridade/IC_PLN/texto9.txt', '/content/analise_similaridade/IC_PLN/texto10.txt',
                  '/content/analise_similaridade/IC_PLN/texto11.txt'
)

# Lendo os textos dos arquivos:

abstrato1 = ler_arquivo(caminho_abstrato[0]).split()
abstrato2 = ler_arquivo(caminho_abstrato[9]).split()

# Calculando a similaridade de Jaccard entre os textos
indice_similaridade = td.jaccard.normalized_similarity(abstrato1, abstrato2)

# Resultado da análise:

print("Similaridade de Jaccard entre os textos:", round(indice_similaridade*100, 3), "%")

